# PID Unit 2
planar_2dof:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joints_position_controller:
    type: my_controller_unit2_unit3_pid/PositionController
    joint1: joint1
    joint2: joint2
    # [P,I,D] gains joint 1
    gains1: [0.0,0.0,0.0]
    # [P,I,D] gains joint 2
    gains2: [0.0,0.0,0.0]
    # theta1, theta2 in degrees
    set_points: [-50.0,-27.0] 